#!/bin/bash -x
# config for the translation tools for Lessons In Electric Circuits (LIEC)

# NOTICE: This repo needs to know where the source LIEC is located - EDIT THIS!
   BE_LIEC_DIR=/root/liec
   export BE_LIEC_DIR

# the basic-electricity repo will fail to function, if it cannot find source
if [ ! -d $BE_LIEC_DIR ]; then
   echo "Please edit the \"factory-settings\" with source location - line 5"
   exit 1 
fi

# use the BE_ prefix (basic electricity), -- since our communication to python
#  is exptremely easy via environment variables -- no clobber existing variables

# setup static varibles
export BE_DIR=$(cd `dirname $0`;pwd)

# make sure there is a build directory
mkdir -p $BE_LIEC_DIR/build

# list of languages -- edit (add or subtract) to specify languages of interest
#    export BE_LANGUAGES_LIST="es fr"
    export BE_LANGUAGES_LIST="en"

# list of volumes -- comprehensive list of places to search for chapters
#    edit to create a subset of volumes to be operated upon
#    export BE_VOLUMES="DC AC Exper Devel Ref Semi"
    export BE_VOLUMES="DC AC"

# list of sml files to translate -- empty list does all languages, volumes in
#     previous two lists
#    export BE_LIST="dsl"
    export BE_LIST="basiccon ohm safety dsl batt basicac s_and_p "

# list of volumes (output lesson names) corresponding to above BE_list
    export BE_LESSONS="DC_1 DC_2 DC_3 DC_5 DC_11 AC_1 AC_A1 AC_A3"

# set up a logfile to record significant events
    export BE_LOGFILE=$BE_DIR/translate.log
