#!/bin/bash -x
# process all the sml files specified in the lists passed from factory

source ./factory-settings

# go over the list of languages
for lang in $BE_LANGUAGES_LIST; do
   mkdir -p $BE_LIEC_DIR/build/$lang
   mkdir -p $BE_LIEC_DIR/build/html/DC
   mkdir -p $BE_LIEC_DIR/build/html/AC

   # copy the whole source context to build directory
   for volume in $BE_VOLUMES; do
      rsync -a --exclude=*.sml $BE_LIEC_DIR/$volume $BE_LIEC_DIR/build/$lang
      cp $BE_DIR/scripts/mk${volume}htmlSubset $BE_LIEC_DIR/build/$lang/$volume
      # substitute our own sed script that knows about <quote> and </quote>
      cp $BE_DIR/scripts/sml2html.sed $BE_LIEC_DIR/build/$lang/$volume
      rm -f $BE_LIEC_DIR/build/$lang/$volume/${volume}_*.html
      # add in the meta tag for UTF-8 to all pages
      hi_filenames=`ls -1 $BE_LIEC_DIR/build/$lang/$volume/hi_*.html`
      for hi_fn in $hi_filenames; do
         grep '.*<meta charset="UTF-8">' $hi_fn       
         if [ $? -ne 0 ]; then
            sed -i -e'/.*<meta name="keywords".*>$/a   <meta charset="UTF-8">' $hi_fn
         fi
      done
   done
   
   # scan through source dirs looking for sml file
   translate_this=

   # if the sml list is empty, the user wants everything
   if [ -z "$BE_LIST" ]; then
      BE_list=`ls $BE_LIEC_DIR/*/*.sml`
   fi

   for smlfile in $BE_LIST;do
      # first find the full path of the smlfile
      for volume in $BE_VOLUMES; do
        if [ -f $BE_LIEC_DIR/$volume/$smlfile ]; then
           translate_this=$BE_LIEC_DIR/$volume/$smlfile
           volumedir=$volume
        else
           # take care of a list of files with out .sml suffix
           if [ -f $BE_LIEC_DIR/$volume/$smlfile.sml ]; then
              translate_this=$BE_LIEC_DIR/$volume/$smlfile.sml
              volumedir=$volume
           fi  
        fi 
      done
      if [ -z "$translate_this" ]; then
          # log a failure to find
          echo "failed to find $smlfile in $BE_VOLUMES" >>$BE_LOGFILE
      else 
         $BE_DIR/scripts/xlate $translate_this $volumedir $lang 
         #echo  "$BE_DIR/scripts/xlate $translate_this $volumedir  $lang" 
      fi
   done
   # done with this smlfile
   # process the sml file to html and collect all html together
   pushd $BE_LIEC_DIR/build/$lang/DC
       ./mkDChtmlSubset
       ls DC_*.html | xargs sed -i -e "s/&amp;#39;/'/g" 
       cp DC_*.html $BE_LIEC_DIR/build/html/DC
   popd
   pushd $BE_LIEC_DIR/build/$lang/AC
       ./mkAChtmlSubset
       ls AC_*.html | xargs sed -i -e "s/&amp;#39;/'/g" 
       cp AC_*.html $BE_LIEC_DIR/build/html/AC
   popd
done
# done with all languages
