#!/bin/bash
# generate html only if the .sml file exists -- hacked from Makefile snippet

# Converts SubML source into HTML source
# toc.map is necessary to htmltoc2 perl script
# added htmltoc2 for mini-table of contnets in chapters
#AC_1.html : basicac.sml hi_1.html bye_1.html sml2html.sed
if [ -f basicac.sml ]; then
	cat hi_1.html > AC_1.html
	sed -f sml2html.sed basicac.sml >> AC_1.html
	cat bye_1.html >> AC_1.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-\minitoc\-\->" AC_1.html 
fi
#AC_2.html : complex.sml hi_2.html bye_2.html sml2html.sed
if [ -f complex.sml ]; then
	cat hi_2.html > AC_2.html
	sed -f sml2html.sed complex.sml >> AC_2.html
	cat bye_2.html >> AC_2.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_2.html
fi

#AC_3.html : xzl.sml hi_3.html bye_3.html sml2html.sed
if [ -f xzl.sml ]; then
	cat hi_3.html > AC_3.html
	sed -f sml2html.sed xzl.sml >> AC_3.html
	cat bye_3.html >> AC_3.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_3.html
fi

#AC_4.html : xzc.sml hi_4.html bye_4.html sml2html.sed
if [ -f xzc.sml ]; then
	cat hi_4.html > AC_4.html
	sed -f sml2html.sed xzc.sml >> AC_4.html
	cat bye_4.html >> AC_4.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
       -minitoc "<\!\-\-minitoc\-\->" AC_4.html
fi

#AC_5.html : xzrlc.sml hi_5.html bye_5.html sml2html.sed
if [ -f xzrlc.sml ]; then
	cat hi_5.html > AC_5.html
	sed -f sml2html.sed xzrlc.sml >> AC_5.html
	cat bye_5.html >> AC_5.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_5.html
fi

#AC_6.html : resonant.sml hi_6.html bye_6.html sml2html.sed
if [ -f resonant.sml ]; then
	cat hi_6.html > AC_6.html
	sed -f sml2html.sed resonant.sml >> AC_6.html
	cat bye_6.html >> AC_6.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_6.html
fi

#AC_7.html : mixed.sml hi_7.html bye_7.html sml2html.sed
if [ -f mixed.sml ]; then
	cat hi_7.html > AC_7.html
	sed -f sml2html.sed mixed.sml >> AC_7.html
	cat bye_7.html >> AC_7.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_7.html
fi

#AC_8.html : filters.sml hi_8.html bye_8.html sml2html.sed
if [ -f filters.sml ]; then
	cat hi_8.html > AC_8.html
	sed -f sml2html.sed filters.sml >> AC_8.html
	cat bye_8.html >> AC_8.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
       -minitoc "<\!\-\-minitoc\-\->" AC_8.html
fi

#AC_9.html : trans.sml hi_9.html bye_9.html sml2html.sed
if [ -f trans.sml ]; then
	cat hi_9.html > AC_9.html
	sed -f sml2html.sed trans.sml >> AC_9.html
	cat bye_9.html >> AC_9.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_9.html
fi

#AC_10.html : poly.sml hi_10.html bye_10.html sml2html.sed
if [ -f poly.sml ]; then
	cat hi_10.html > AC_10.html
	sed -f sml2html.sed poly.sml >> AC_10.html
	cat bye_10.html >> AC_10.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_10.html
fi

#AC_11.html : acpower.sml hi_11.html bye_11.html sml2html.sed
if [ -f acpower.sml ]; then
	cat hi_11.html > AC_11.html
	sed -f sml2html.sed acpower.sml >> AC_11.html
	cat bye_11.html >> AC_11.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_11.html
fi

#AC_12.html : acmeter.sml hi_12.html bye_12.html sml2html.sed
if [ -f acmeter.sml ]; then
	cat hi_12.html > AC_12.html
	sed -f sml2html.sed acmeter.sml >> AC_12.html
	cat bye_12.html >> AC_12.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_12.html
fi

#AC_13.html : acmotor.sml hi_13.html bye_13.html sml2html.sed
if [ -f acmotor.sml ]; then
	cat hi_13.html > AC_13.html
	sed -f sml2html.sed acmotor.sml >> AC_13.html
	cat bye_13.html >> AC_13.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_13.html
fi

#AC_14.html : lines.sml hi_14.html bye_14.html sml2html.sed
if [ -f lines.sml ]; then
	cat hi_14.html > AC_14.html
	sed -f sml2html.sed lines.sml >> AC_14.html
	cat bye_14.html >> AC_14.html
	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map \
        -minitoc "<\!\-\-minitoc\-\->" AC_14.html
fi

#AC_A1.html : about.sml hi_A1.html bye_A1.html sml2html.sed
if [ -f about.sml ]; then
	cat hi_A1.html > AC_A1.html
	sed -f sml2html.sed about.sml >> AC_A1.html
	cat bye_A1.html >> AC_A1.html
#	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map AC_A1.html
fi


#AC_A2.html : contrib.sml hi_A2.html bye_A2.html sml2html.sed
if [ -f contrib.sml ]; then
	cat hi_A2.html > AC_A2.html
	sed -f sml2html.sed contrib.sml >> AC_A2.html
	cat bye_A2.html >> AC_A2.html
#	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map AC_A2.html
fi

#AC_A3.html : dsl.sml hi_A3.html bye_A3.html sml2html.sed
if [ -f dsl.sml ]; then
	cat hi_A3.html > AC_A3.html
	sed -f sml2html.sed dsl.sml >> AC_A3.html
	cat bye_A3.html >> AC_A3.html
#	./htmltoc2 -inline -noorg  -toclabel " " -tocmap toc.map AC_A3.html
fi


